Repository GTNewHorizons/GT-New-Horizons-Modpack, pull requests merged in 2024-10, with the labels that each got.

#17565 Buff Hydroponics Unit.
  config/GalacticraftAmunRa.cfg
Labels: Type: Balancing, Mod: Amunra, Pull Request: Affects Balance

#17664 fix uua speed bonus
  config/GregTech/MachineStats.cfg
Labels: bug fix

#17749 Fix akashic tome quest
  config/betterquesting/DefaultQuests/Quests/Tier05Steam-AAAAAAAAAAAAAAAAAAAAAg==/Theonebooktorule-XuZpnhWZRou46kensglZ6g==.json
Labels: Type: bugMajor, bug fix

#17803 remove quest mention of deleted chunk loader machine
  config/betterquesting/DefaultQuests/Quests/AndSoItBegins-AAAAAAAAAAAAAAAAAAAAAA==/LoadingtheChunks-AAAAAAAAAAAAAAAAAAALOg==.json
Labels: bug fix
