Repository GTNewHorizons/GT-New-Horizons-Modpack, pull requests merged in 2024-09, with the labels that each got.

#17232 More tgregworks removals
  config/TGregworks.cfg
Labels: Type: Enhancement

#17248 Add quests for beamline multis + general beamline info
  config/betterquesting/DefaultQuests/QuestLines/MultiblockGoals-AAAAAAAAAAAAAAAAAAAADA==/ABeginnersGuidet-NGG2rHQ4T4SInwXT8XTGSg==.json
  config/betterquesting/DefaultQuests/QuestLines/MultiblockGoals-AAAAAAAAAAAAAAAAAAAADA==/CollisionCourse-9Pc7p99ASnybsIbWmmg0LQ==.json
  config/betterquesting/DefaultQuests/QuestLines/MultiblockGoals-AAAAAAAAAAAAAAAAAAAADA==/HundredsofThousa-Y1kiJC_kRGKkW7h3qOPI8A==.json
  config/betterquesting/DefaultQuests/QuestLines/MultiblockGoals-AAAAAAAAAAAAAAAAAAAADA==/NoMoreICEngravin-isBmh7T0Sr63O2m5N4pCIQ==.json
  config/betterquesting/DefaultQuests/QuestLines/MultiblockGoals-AAAAAAAAAAAAAAAAAAAADA==/SynchrotronNoRel-QfQHCy0PRn-rABmKuvwQfw==.json
  config/betterquesting/DefaultQuests/Quests/MultiblockGoals-AAAAAAAAAAAAAAAAAAAADA==/ABeginnersGuidet-NGG2rHQ4T4SInwXT8XTGSg==.json
  config/betterquesting/DefaultQuests/Quests/MultiblockGoals-AAAAAAAAAAAAAAAAAAAADA==/CollisionCourse-9Pc7p99ASnybsIbWmmg0LQ==.json
  config/betterquesting/DefaultQuests/Quests/MultiblockGoals-AAAAAAAAAAAAAAAAAAAADA==/HundredsofThousa-Y1kiJC_kRGKkW7h3qOPI8A==.json
  config/betterquesting/DefaultQuests/Quests/MultiblockGoals-AAAAAAAAAAAAAAAAAAAADA==/NoMoreICEngravin-isBmh7T0Sr63O2m5N4pCIQ==.json
  config/betterquesting/DefaultQuests/Quests/MultiblockGoals-AAAAAAAAAAAAAAAAAAAADA==/SynchrotronNoRel-QfQHCy0PRn-rABmKuvwQfw==.json
Labels: Type: New Quests

#17372 Quest improvements - 17 September
  config/betterquesting/DefaultQuests/QuestLines/Tier0StoneAge-AAAAAAAAAAAAAAAAAAAAAQ==/AnotherBrickinth-AAAAAAAAAAAAAAAAAAAAGQ==.json
  config/betterquesting/DefaultQuests/QuestLines/Tier11UIV-ytf2QCzUSk6ihcYeRbwblw==/AssemblingonSter-WJ-SykCeTr2B-3SHz0mXZg==.json
  config/betterquesting/DefaultQuests/QuestLines/Tier11UIV-ytf2QCzUSk6ihcYeRbwblw==/DysonSwarmGround-AAAAAAAAAAAAAAAAAAAL3w==.json
  config/betterquesting/DefaultQuests/QuestLines/Tier11UIV-ytf2QCzUSk6ihcYeRbwblw==/HahaSpinnyIngot-Jk9jZtb6SXSLNX9SND_J0A==.json
  config/betterquesting/DefaultQuests/QuestLines/Tier11UIV-ytf2QCzUSk6ihcYeRbwblw==/NanoForgeTier3-AAAAAAAAAAAAAAAAAAAM0Q==.json
  config/betterquesting/DefaultQuests/QuestLines/Tier11UIV-ytf2QCzUSk6ihcYeRbwblw==/SpaceModulesGalo-nghPgh6-TuSKXUlzGXGrpw==.json
  config/betterquesting/DefaultQuests/QuestLines/Tier11UIV-ytf2QCzUSk6ihcYeRbwblw==/ThaumometricEsse-xdiDnTdpTgW6POwCuDlPgg==.json
  config/betterquesting/DefaultQuests/QuestLines/Tier11UIV-ytf2QCzUSk6ihcYeRbwblw==/TheCatisOutofthe-RAH2M4DoTTaX5a2Sj4hRcQ==.json
  config/betterquesting/DefaultQuests/QuestLines/Tier11UIV-ytf2QCzUSk6ihcYeRbwblw==/TheRealPlanetEat-GHobGJFEQzK1q96l6oC8wQ==.json
  config/betterquesting/DefaultQuests/QuestLines/Tier11UIV-ytf2QCzUSk6ihcYeRbwblw==/TranscendentPlas-KGDOhsZGQv2QqDzGdI_YTg==.json
  config/betterquesting/DefaultQuests/QuestLines/Tier11UIV-ytf2QCzUSk6ihcYeRbwblw==/UIVFieldGenerato-q6WN7XY8Qf6PNgWTy7RrBA==.json
  config/betterquesting/DefaultQuests/QuestLines/Tier11UIV-ytf2QCzUSk6ihcYeRbwblw==/UMVCircuits-AAAAAAAAAAAAAAAAAAAMqg==.json
  config/betterquesting/DefaultQuests/QuestLines/Tier11UIV-ytf2QCzUSk6ihcYeRbwblw==/WhereDoIBuildthe-AAAAAAAAAAAAAAAAAAAL4A==.json
  config/betterquesting/DefaultQuests/QuestLines/Tier11UIV-ytf2QCzUSk6ihcYeRbwblw==/YouKnowtheDrillp-AAAAAAAAAAAAAAAAAAAMpQ==.json
  config/betterquesting/DefaultQuests/QuestLines/Tier12UMV-l37V2WvbSHGZQ5oMgAfBuw==/GuzzlingMassiveA-5vAyoCzxQkSRpjzlDNwtrw==.json
  config/betterquesting/DefaultQuests/QuestLines/Tier12UMV-l37V2WvbSHGZQ5oMgAfBuw==/PowerintheEther-AAAAAAAAAAAAAAAAAAAMow==.json
  config/betterquesting/DefaultQuests/QuestLines/Tier12UMV-l37V2WvbSHGZQ5oMgAfBuw==/SubspaceCooling-hybMIjq9Q9mxxWKEE8gBWQ==.json
  config/betterquesting/DefaultQuests/QuestLines/Tier12UMV-l37V2WvbSHGZQ5oMgAfBuw==/ThermosinkRadiat-AAAAAAAAAAAAAAAAAAAMzQ==.json
  config/betterquesting/DefaultQuests/QuestLines/Tier12UMV-l37V2WvbSHGZQ5oMgAfBuw==/YetAnotherSpaceE-MiGXZ65sRwiAdpsCrVB0Eg==.json
  config/betterquesting/DefaultQuests/QuestLines/Tier1LV-AAAAAAAAAAAAAAAAAAAAAw==/ElectricMacerato-AAAAAAAAAAAAAAAAAAAAXg==.json
  config/betterquesting/DefaultQuests/Quests/NoviceThaumaturg-AAAAAAAAAAAAAAAAAAAAFg==/Stores50VisWand-AAAAAAAAAAAAAAAAAAAA7Q==.json
  config/betterquesting/DefaultQuests/Quests/Tier0StoneAge-AAAAAAAAAAAAAAAAAAAAAQ==/AnotherBrickinth-AAAAAAAAAAAAAAAAAAAAGQ==.json
  config/betterquesting/DefaultQuests/Quests/Tier0StoneAge-AAAAAAAAAAAAAAAAAAAAAQ==/GettingCharcoal-AAAAAAAAAAAAAAAAAAAAGA==.json
  config/betterquesting/DefaultQuests/Quests/Tier12UMV-l37V2WvbSHGZQ5oMgAfBuw==/TheDarknessofCho-AAAAAAAAAAAAAAAAAAAJbQ==.json
  config/betterquesting/DefaultQuests/Quests/Tier1LV-AAAAAAAAAAAAAAAAAAAAAw==/BasicOreWasher-AAAAAAAAAAAAAAAAAAACGg==.json
  config/betterquesting/DefaultQuests/Quests/Tier1LV-AAAAAAAAAAAAAAAAAAAAAw==/CompactOrisit-AAAAAAAAAAAAAAAAAAACIA==.json
  config/betterquesting/DefaultQuests/Quests/Tier1LV-AAAAAAAAAAAAAAAAAAAAAw==/ElectricMacerato-AAAAAAAAAAAAAAAAAAAAXg==.json
  config/betterquesting/DefaultQuests/Quests/Tier1LV-AAAAAAAAAAAAAAAAAAAAAw==/HeyDJMixit-AAAAAAAAAAAAAAAAAAACKg==.json
  config/betterquesting/DefaultQuests/Quests/Tier1LV-AAAAAAAAAAAAAAAAAAAAAw==/Mjolnir-AAAAAAAAAAAAAAAAAAAAZQ==.json
  config/betterquesting/DefaultQuests/Quests/Tier1LV-AAAAAAAAAAAAAAAAAAAAAw==/RoundandRoundand-AAAAAAAAAAAAAAAAAAACGw==.json
Labels: bug fix

#17463 remove gt arrows from lootpools
  config/TooMuchLoot/loot/pyramidJungleDispenser.xml
  config/TooMuchLoot/loot/strongholdCorridor.xml
Labels: bug fix

#17504 Quest fixes - 28 September
  config/betterquesting/DefaultQuests/QuestLines/Tier5IV-AAAAAAAAAAAAAAAAAAAABw==/ASmallRewardTheI-n22vWzZHSu6Gn63EBV1FUw==.json
  config/betterquesting/DefaultQuests/Quests/Tier3HV-AAAAAAAAAAAAAAAAAAAABQ==/Rutile-AAAAAAAAAAAAAAAAAAAD9A==.json
  config/betterquesting/DefaultQuests/Quests/Tier5IV-AAAAAAAAAAAAAAAAAAAABw==/ASmallRewardTheI-n22vWzZHSu6Gn63EBV1FUw==.json
  config/betterquesting/DefaultQuests/Quests/Tier5IV-AAAAAAAAAAAAAAAAAAAABw==/IVMixer-AAAAAAAAAAAAAAAAAAAFgg==.json
  config/betterquesting/DefaultQuests/Quests/Tier5IV-AAAAAAAAAAAAAAAAAAAABw==/Thorium232-nNTmwkdsQgyE6QAfmIwcvg==.json
Labels: bug fix
